version: 3
endpoint: http://localhost:8080
admin_secret: supersecretkey
metadata_directory: metadata
migrations_directory: migrations
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
